apiVersion: v1
kind: Secret
metadata:
  name: server-a-certs
  labels:
    name: server-a-certs
  annotations:
    description: Certificate for server a
type: Opaque
data:
  server.key: {{ .Files.Get "files/server.key" | b64enc }}
  server.crt: {{ .Files.Get "files/server.crt" | b64enc }}