apiVersion: v1
kind: Service
metadata:
  name: server-a-svc
  labels:
    app: server-a-app
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
  - port: 8443
    name: https
    protocol: TCP
  selector:
    app: server-a-app
---
apiVersion: v1
kind: Service
metadata:
  name: server-b-svc
  labels:
    app: server-b-app
spec:
  ports:
  - port: 9080
    name: http
    protocol: TCP
  selector:
    app: server-b-app