apiVersion: v2
appVersion: "9.4"
description: This Helm Chart deploys the STS Gateway in Kubernetes
name: sts
version: 1.0.1
dependencies:
- name: hazelcast
  version: ^1.1.0
  repository: "@stable"
  condition: hazelcast.enabled
- name: mysql
  version: ^1.6.2
  repository: "@stable"
  condition: mysql.enabled
- name: influxdb
  version: ^1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: grafana
  version: 1.21.2
  repository: https://kubernetes-charts.storage.googleapis.com/