apiVersion: v2
appVersion: "9.4"
description: This Helm Chart deploys the EDGE Gateway in Kubernetes along with an STS Gateway, hazelcast, grafana, influxdb and reloader
name: layer7
version: 1.0.1
dependencies:
- name: hazelcast
  version: ^1.1.0
  repository: "@stable"
  condition: hazelcast.enabled
- name: sts
  version: 1.0.1
  repository: "@layer7"
  condition: sts.enabled
- name: demo
  version: 1.0.0
  repository: "@layer7"
  condition: demo.enabled