{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gateway-ingress
spec:
  host: {{ template "edge.gateway.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
{{ end }}