apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "sts.gateway.fullname" . }}
  labels:
    app: {{ template "sts.gateway.name" . }}
    chart: {{ template "sts.gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- if .Values.updateStrategy }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "sts.gateway.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
{{- if eq .Values.global.version "9.4" }}
          image: {{ .Values.container.image }}:1.0
{{- else if eq .Values.global.version "10.0" }}
          image: {{ .Values.container.image }}:2.0
{{- end }}  
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .internal }}
            {{- end }}
          volumeMounts:
{{- if  .Values.gateway.customTlsKey.enabled }}
            - name: sts-gateway-certs
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/config/privateKeys
{{- end }}
            - name: {{ template "sts.gateway.fullname" . }}-license-xml
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
              subPath: license.xml
            - name: {{ template "sts.gateway.fullname" . }}-hazelcast-client
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/assertions/ExternalHazelcastSharedStateProviderAssertion/hazelcast-client.xml
              subPath: hazelcast-client.xml
            - name: {{ template "sts.gateway.fullname" . }}-log-config-override
              mountPath: /opt/SecureSpan/Gateway/node/default/etc/conf/log-override.properties
              subPath: log-override.properties
          envFrom:
            - configMapRef:
                name: {{ template "sts.gateway.fullname" . }}
          env:
  
{{- range $name, $value := .Values.gateway.env }}
{{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
              - /opt/docker/rc.d/diagnostic/health_check.sh
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
              - /opt/docker/rc.d/diagnostic/health_check.sh
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
{{- end }}
      volumes:
{{- if  .Values.gateway.customTlsKey.enabled }}
        - name: sts-gateway-certs
          secret:
            secretName: sts-gateway-certs
{{- end }}
        - name: {{ template "sts.gateway.fullname" . }}-license-xml
          secret:
            secretName: {{ template "sts.gateway.fullname" .}}-license
            items:
            - key: license
              path: license.xml
        - name: {{ template "sts.gateway.fullname" . }}-hazelcast-client
          configMap:
            name: {{ template "sts.gateway.fullname" . }}
            items:
            - key: hazelcast-xml
              path: hazelcast-client.xml
        - name: {{ template "sts.gateway.fullname" . }}-log-config-override
          configMap:
            name: {{ template "sts.gateway.fullname" . }}
            items:
            - key: log-override-properties
              path: log-override.properties