apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sts.gateway.fullname" .}}-license
  labels:
    name: gw-license
  annotations:
    description: Template for Secrets for the Gateway license
type: Opaque
data:
  license: {{ .Values.global.license.value | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sts.gateway.fullname" .}}-certs
  labels:
    name: sts-gateway-certs
  annotations:
    description: This is a packaged private key pair that we ship with for testing purposes, if you'd like to replace this then make sure you update the edge gateway too.
type: Opaque
data:
  ssl.p12: {{ .Files.Get "files/ssl.p12" | b64enc | quote }}