apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "sts.gateway.fullname" . }}
    chart: {{ template "sts.gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "sts.gateway.fullname" . }}
  annotations:
    description: "The STS Gateway service"
spec:
  selector:
    app: {{ template "sts.gateway.fullname" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
{{- range .Values.service.ports }}
    - protocol: TCP
      port: {{ .external }}
      targetPort: {{ .internal }}
      name: {{ .name | quote }}
{{- end }}