apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: h1
 namespace: istio-system
spec:
 adapter: layer7authadapter
 connection:
   #address: "[::]:44225"
   address: "layer7authadapterservice:44225"
   #address: "35.184.34.117:44225"
 params:
   auth_key: "abc"
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: icheck
 namespace: istio-system
spec:
 template: authorization
 params:
   subject:
     # These properties become arguments passed into the adapter
     # and used by: decodeValueMap(r.Instance.Subject.Properties)
     properties:
       auth_token_header:  request.headers["authorization"]
       custom_token_header:  request.headers["x-custom-token"]
       fingerprint_header: request.headers["x-src"]
       # Those headers must be listed here lowercase, even though
       # in the actual HTTP request they may be capitalized
---
# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: r1
 namespace: istio-system
spec:
 #match: destination.service.host == "server-a-svc.default.svc.cluster.local"
 match: match(destination.service.host, "server-a-svc*")
 actions:
 - handler: h1.istio-system
   instances:
   - icheck
---
