# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-metrics-grafana-example:
    hostname: localhost
    build: .
    image: gateway-metrics-grafana-example
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      EXTRA_JAVA_ARGS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    environment:
      INFLUXDB_DB: "serviceMetricsDb"

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-config/service-metrics-datasource.yml:/etc/grafana/provisioning/datasources/service-metrics-datasource.yml
      - ./grafana-config/service-metrics-dashboard.yml:/etc/grafana/provisioning/dashboards/service-metrics-dashboard.yml
      - ./grafana-config/Gateway-Service-Metrics-Dashboard.json:/var/lib/grafana/dashboards/Gateway-Service-Metrics-Dashboard.json
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "password"

  http-echo:
    image: hashicorp/http-echo:latest
    hostname: http-echo
    command: -text="This is a response from http-echo server."

secrets:
  license:
    file: ./docker/license.xml
